CREATE  TABLE IF NOT EXISTS futbolistas (
  `id` INT(4) NOT NULL AUTO_INCREMENT ,
  `nombre` VARCHAR(100) NOT NULL ,
  `apellido` VARCHAR(100) NULL ,
  `posicion` VARCHAR(50) NULL ,
  `equipo` VARCHAR(50) NULL ,
  `dorsal` INT(1) NULL ,
  `desc` VARCHAR(400) NULL ,
  `imagen` VARCHAR(50) NULL ,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

insert into futbolistas values (1, "Gareth Frank","Bale", "Centrocampista","Real Madrid", 11, "El portentoso jugador galés es la gran apuesta del equipo blanco para esta temporada. Velocidad, técnica y potencia son sus grandes cualidades, por lo que está llamado a formar una de las mejores duplas de ataque junto a Cristiano Ronaldo.", "bale.jpg");
insert into futbolistas values (2, "Iker", "Casillas", "Portero", "Real Madrid", "1", "Leyenda viva del Real Madrid y de la selección española, con quienes lo ha conquistado absolutamente todo. El capitán blanco siempre destacó por sus excelentes reflejos y sus paradas imposibles y decisivas. Esta temporada peleará por el puesto de titular con Diego López, quien lo sustituyó con garantías tras sufrir una desafortunada lesión la pasada campaña.", "casillas.jpg");
insert into futbolistas values (3, "Ángel Fabián", "Di María", "Centrocampista", "Real Madrid", 22,"El argentino llamó la atención de numerosos clubes europeos en el Benfica, donde ganó un título de liga y llegó a ser considerado el mejor jugador del campeonato. El Real Madrid fue quien se hizo finalmente con sus servicios y durante tres temporadas ha sido un jugador muy importante. Extremo zurdo muy habilidoso, desequilibrante y con gran olfato de gol. Puede jugar por ambas bandas.", "dimaria.jpg");
insert into futbolistas values (4, "Andrés", "Iniesta", "Centrocampista","F.C.Barcelona", 8, "Inteligencia, visión de juego, verticalidad y mucha elegancia son algunas de sus innumerables cualidades. El manchego es uno de los faros que iluminan el alegre juego del Barcelona y de la selección española y uno de los mejores centrocampistas del fútbol mundial.", "iniesta.jpg");
insert into futbolistas values (5, "Jesé", "Rodriguez", "Delantero", "Real Madrid", 20, "Una de las grandes joyas de la cantera madridista. La pasada temporada fue uno de los máximos anotadores de la Liga Adelante tras conseguir 22 goles con el Castilla, superando el récord de tantos de Emilio Butragueño con el filial (21). Rápido y muy desequilibrante, puede desempeñarse como extremo o ser referencia en la punta de ataque. En su primera temporada como parte del primer equipo intentará demostrar sus grandes cualidades y ganarse la confianza de Carlo Ancelotti.", "jese.jpg");
insert into futbolistas values (6, "Marcelo", "Vieira da Silva", "Defensa", "Real Madrid", 12, "Con apenas 18 años fichó por el Real Madrid y, desde entonces, fue creciendo poco a poco hasta convertirse en uno de los mejores en su puesto. La sombra de su compatriota Roberto Carlos era alargada, pero Marcelo se ganó el cariño de la afición gracias a sus peligrosas subidas, numerosas asistencias y goles y una notable mejoría en el aspecto defensivo.", "marcelo.jpg");
insert into futbolistas values (7, "Lionel Andrés", "Messi", "Delantero", "F.C.Barcelona", 10, "Pura fantasía en las botas. Galardonado en cuatro ocasiones con el Balón de Oro, es uno de esos jugadores capaces de decidir cualquier partido gracias a su velocidad, regate, explosividad y efectividad goleadora. Considerado uno de los mejores futbolistas de la historia del fútbol, el argentino intentará seguir agrandando su leyenda junto al recién llegado Neymar.", "messi.jpg");
insert into futbolistas values (8, "Luka", "Modric","Centrocampista", "Real Madrid",19, "Sus buenas actuaciones con el Dínamo de Zagreb lo llevaron a dar el salto a Inglaterra, donde jugó a un excelente nivel en el Tottenham durante cuatro temporadas. Llegó al Real Madrid en el verano de 2012 y con el paso de los meses fue adquiriendo mayor protagonismo, contando con minutos en 33 partidos de liga en los que anotó tres goles. En esta nueva campaña intentará convencer a Ancelotti de que hay un sitio para él en el centro del campo.", "modric.jpg");
insert into futbolistas values (9, "Neymar", "da Silva", "Delantero", "F.C.Barcelona", 11, "La gran estrella del fútbol brasileño y el jugador más deseado en Europa llega a la Liga BBVA. Es un futbolista muy completo: tiene velocidad, regate, disparo y gran efectividad goleadora. Junto a Messi, formarán una de las parejas más temidas del continente. El espectáculo está asegurado.", "neymar.jpg");
insert into futbolistas values ( 10, "Pedro", "Rodríguez", "Delantero", "F.C.Barcelona", 7, "Desde su ascenso al primer equipo de la mano de Guardiola, el canario devolvió la confianza depositada en él con goles y grandes actuaciones. Sus condiciones tampoco pasaron desapercibidas para Vicente del Bosque, que lo reclutó para la selección española y fue parte del equipo campeón del Mundial 2010 y la Eurocopa de 2012.", "pedro.jpg");
insert into futbolistas values ( 11, "Gerard", "Piqué", "Defensa", "F.C.Barcelona", 3, "Tras militar en el Manchester United, en 2008 volvió al club en el que se formó como jugador para convertirse en uno de los mejores centrales del mundo. Su gran estatura lo convierte en un jugador muy poderoso en el juego aéreo. Además, goza de una buena calidad técnica para sacar el balón desde atrás y sumarse al ataque.", "pique.jpg");
insert into futbolistas values ( 12, "Carles", "Puyol", "Defensa", "F.C.Barcelona", 5, "Toda una institución en el club. En sus 14 años defendiendo los colores del Barcelona, el gran capitán lo ha ganado absolutamente todo. La pasada campaña sólo pudo disputar 15 partidos de Liga, pero su fortaleza, seguridad y jerarquía en el eje de la zaga hacen de él un jugador insustituible.", "puyol.jpg");
insert into futbolistas values ( 13, "Cristiano", "Ronaldo", "Delantero", "Real Madrid", 7, "Futbolista todoterreno, uno de los más completos del mundo. Posee un excelente golpeo con ambas piernas, una enorme superioridad en el juego aéreo y una gran velocidad y regate para superar a cualquier adversario. Tras triunfar en el Manchester United, llegó a la capital española en 2009 en lo que fue el traspaso más caro de la historia del fútbol. Desde entonces, ha sido el emblema del equipo y el gran ídolo de la afición. Sus 146 goles en 135 partidos de liga durante cuatro temporadas hablan por sí solos.", "ronaldo.jpg");
insert into futbolistas values ( 14, "Sergio", "Ramos", "Defensa", "Real Madrid", 4, "Aterrizó en la capital tras brillar con el Sevilla con apenas 19 años. Desde entonces, el futbolista de Camas ha sido un jugador insustituible en la defensa blanca, primero como lateral derecho y posteriormente como central. Fuerte y poderoso por alto, un muro infranqueable con mucho gol.", "ramos.jpg");
insert into futbolistas values ( 15, "Victor", "Valdés", "Portero", "F.C.Barcelona", 1, "El experimentado guardameta volverá a defender la portería azulgrana tras más de diez temporadas en la élite. Galardonado en cinco ocasiones con el Trofeo Zamora al portero menos goleado, destaca por sus enormes reflejos, manejo de los pies y liderazgo en el terreno de juego.", "victorvaldes.jpg");
insert into futbolistas values ( 16, "Xabi", "Alonso", "Centrocampista", "Real Madrid", 14, "Un jugador insustituible durante sus cuatro años en el conjunto blanco. Despuntó muy joven en la Real Sociedad y con 23 años emigró a Inglaterra para crecer en el Liverpool, donde conquistó una Champions. Fichó por el Madrid en 2009 para ser el cerebro del equipo, un rol que continúa desempeñando a la perfección.",  "xabi.jpg");
insert into futbolistas values ( 17, "Xavi", "Hernández", "Centrocampista", "F.C.Barcelona", 6, "El cerebro del Barcelona. Todo un director de orquesta: dirige, organiza el juego y siempre encuentra la mejor solución, por complicada que parezca. Afronta su decimosexta temporada en el equipo tras haberlo ganarlo todo con la camiseta blaugrana y de la selección española.", "xavi.jpg");

